using System.Text;
using System;

namespace Stardust.Generators;

public partial class BitFieldsGenerator
{
    /// <summary>
    /// Generates a BitField property referencing named mask constants for maximum performance.
    /// For signed property types (sbyte, short, int, long), sign extension is performed
    /// when the field width is smaller than the property type width.
    /// </summary>
    private static void GenerateBitFieldProperty(StringBuilder sb, BitFieldsInfo info, BitFieldInfo field, string indent)
    {
        int shift = field.Shift;
        int width = field.Width;
        int endBit = shift + width - 1;

        // Reference the named mask constants generated by GenerateFieldConstants
        string snakeName = ToUpperSnakeCase(field.Name);
        string maskHex = $"{snakeName}_MASK";
        string shiftedMaskHex = shift > 0 ? $"{snakeName}_SHIFTED_MASK" : $"{snakeName}_MASK";
        string invertedMaskHex = $"{snakeName}_INVERTED_MASK";

        // Check if the property type is signed and needs sign extension
        bool propertyTypeIsSigned = IsSignedType(field.PropertyType);
        int propertyTypeBitWidth = GetTypeBitWidth(field.PropertyType);
        bool needsSignExtension = propertyTypeIsSigned && width < propertyTypeBitWidth;

        sb.AppendLine($"{indent}public partial {field.PropertyType} {field.Name}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        
        // Getter: For signed property types with field width < type width, perform sign extension
        if (needsSignExtension)
        {
            // Optimized sign extension: mask in place, then shift left/right for sign extension.
            // This is more efficient than extract-then-extend (saves one shift operation).
            // Formula: ((signExtendType)(Value & shiftedMask) << leftShift) >> rightShift
            // - leftShift positions the field's MSB at the sign bit of the intermediate type
            // - rightShift propagates the sign and moves the result to bits [0, width-1]
            string signExtendType = GetSignExtendIntermediateType(field.PropertyType);
            int intermediateTypeBitWidth = signExtendType == "long" ? 64 : 32;
            int leftShift = intermediateTypeBitWidth - 1 - endBit;  // Put field MSB at bit 31 (or 63)
            int rightShift = intermediateTypeBitWidth - width;       // Propagate sign to result width
            
            if (info.StorageTypeIsSigned)
            {
                // For signed storage, cast to unsigned first to avoid unwanted sign extension
                sb.AppendLine($"{indent}    get => ({field.PropertyType})((({signExtendType})((({info.UnsignedStorageType})Value) & {shiftedMaskHex}) << {leftShift}) >> {rightShift});");
            }
            else
            {
                sb.AppendLine($"{indent}    get => ({field.PropertyType})((({signExtendType})(Value & {shiftedMaskHex}) << {leftShift}) >> {rightShift});");
            }
        }
        else
        {
            // No sign extension needed - original behavior
            if (info.StorageTypeIsSigned)
            {
                if (shift == 0)
                {
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})((({info.UnsignedStorageType})Value) & {maskHex});");
                }
                else
                {
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})(((({info.UnsignedStorageType})Value) >> {shift}) & {maskHex});");
                }
            }
            else
            {
                if (shift == 0)
                {
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})(Value & {maskHex});");
                }
                else
                {
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})((Value >> {shift}) & {maskHex});");
                }
            }
        }

        sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");

        // Setter: enforce MustBe constraints, or do normal read-modify-write
        if (field.ValueOverride == MustBe.Zero)
        {
            // MustBe.Zero: always clear the field bits regardless of input
            if (info.StorageTypeIsSigned)
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})((({info.UnsignedStorageType})Value) & {invertedMaskHex});");
            else
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})(Value & {invertedMaskHex});");
        }
        else if (field.ValueOverride == MustBe.One)
        {
            // MustBe.One: always set the field bits regardless of input
            if (info.StorageTypeIsSigned)
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})((({info.UnsignedStorageType})Value) | {shiftedMaskHex});");
            else
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})(Value | {shiftedMaskHex});");
        }
        else if (info.StorageTypeIsSigned)
        {
            if (shift == 0)
            {
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})(((({info.UnsignedStorageType})Value) & {invertedMaskHex}) | ((({info.UnsignedStorageType})value) & {shiftedMaskHex}));");
            }
            else
            {
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})(((({info.UnsignedStorageType})Value) & {invertedMaskHex}) | (((({info.UnsignedStorageType})value) << {shift}) & {shiftedMaskHex}));");
            }
        }
        else
        {
            if (shift == 0)
            {
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})((Value & {invertedMaskHex}) | ((({info.StorageType})value) & {shiftedMaskHex}));");
            }
            else
            {
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})((Value & {invertedMaskHex}) | (((({info.StorageType})value) << {shift}) & {shiftedMaskHex}));");
            }
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a BitFlag property referencing named mask constants for maximum performance.
    /// </summary>
    private static void GenerateBitFlagProperty(StringBuilder sb, BitFieldsInfo info, BitFlagInfo flag, string indent)
    {
        // Reference the named mask constants generated by GenerateFieldConstants
        string snakeName = ToUpperSnakeCase(flag.Name);
        string maskHex = $"{snakeName}_MASK";
        string invertedMaskHex = $"{snakeName}_INVERTED_MASK";

        sb.AppendLine($"{indent}public partial bool {flag.Name}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        
        if (flag.ValueOverride == MustBe.Zero)
        {
            // MustBe.Zero: getter always false, setter always clears
            sb.AppendLine($"{indent}    get => false;");
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            if (info.StorageTypeIsSigned)
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})((({info.UnsignedStorageType})Value) & {invertedMaskHex});");
            else
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})(Value & {invertedMaskHex});");
        }
        else if (flag.ValueOverride == MustBe.One)
        {
            // MustBe.One: getter always true, setter always sets
            sb.AppendLine($"{indent}    get => true;");
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            if (info.StorageTypeIsSigned)
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})((({info.UnsignedStorageType})Value) | {maskHex});");
            else
                sb.AppendLine($"{indent}    set => Value = ({info.StorageType})(Value | {maskHex});");
        }
        else if (info.StorageTypeIsSigned)
        {
            sb.AppendLine($"{indent}    get => ((({info.UnsignedStorageType})Value) & {maskHex}) != 0;");
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    set => Value = value ? ({info.StorageType})((({info.UnsignedStorageType})Value) | {maskHex}) : ({info.StorageType})((({info.UnsignedStorageType})Value) & {invertedMaskHex});");
        }
        else
        {
            sb.AppendLine($"{indent}    get => (Value & {maskHex}) != 0;");
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    set => Value = value ? ({info.StorageType})(Value | {maskHex}) : ({info.StorageType})(Value & {invertedMaskHex});");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a static property that returns a struct with only the specified bit set.
    /// </summary>
    private static void GenerateStaticBitProperty(StringBuilder sb, BitFieldsInfo info, BitFlagInfo flag, string indent)
    {
        string maskRef = $"{ToUpperSnakeCase(flag.Name)}_MASK";

        string castExpr = info.StorageTypeIsSigned 
            ? $"unchecked(({info.StorageType}){maskRef})"
            : maskRef;

        sb.AppendLine($"{indent}/// <summary>Returns a {info.TypeName} with only the {flag.Name} bit set.</summary>");
        sb.AppendLine($"{indent}public static {info.TypeName} {flag.Name}Bit => new({castExpr});");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a static property that returns a struct with the mask for the specified field.
    /// </summary>
    private static void GenerateStaticMaskProperty(StringBuilder sb, BitFieldsInfo info, BitFieldInfo field, string indent)
    {
        string snakeName = ToUpperSnakeCase(field.Name);
        string shiftedMaskRef = field.Shift > 0 ? $"{snakeName}_SHIFTED_MASK" : $"{snakeName}_MASK";

        string castExpr = info.StorageTypeIsSigned 
            ? $"unchecked(({info.StorageType}){shiftedMaskRef})"
            : shiftedMaskRef;

        sb.AppendLine($"{indent}/// <summary>Returns a {info.TypeName} with the mask for the {field.Name} field (bits {field.Shift}-{field.Shift + field.Width - 1}).</summary>");
        sb.AppendLine($"{indent}public static {info.TypeName} {field.Name}Mask => new({castExpr});");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a With{Name} method for a BitFlag that returns a new struct with the flag set/cleared.
    /// </summary>
    private static void GenerateWithBitFlagMethod(StringBuilder sb, BitFieldsInfo info, BitFlagInfo flag, string indent)
    {
        // Reference the named mask constants generated by GenerateFieldConstants
        string snakeName = ToUpperSnakeCase(flag.Name);
        string maskHex = $"{snakeName}_MASK";
        string invertedMaskHex = $"{snakeName}_INVERTED_MASK";

        sb.AppendLine($"{indent}/// <summary>Returns a new {info.TypeName} with the {flag.Name} flag set to the specified value.</summary>");
        sb.AppendLine($"{indent}[MethodImpl(MethodImplOptions.AggressiveInlining)]");

        if (info.StorageTypeIsSigned)
        {
            sb.AppendLine($"{indent}public {info.TypeName} With{flag.Name}(bool value) => new(value ? ({info.StorageType})((({info.UnsignedStorageType})Value) | {maskHex}) : ({info.StorageType})((({info.UnsignedStorageType})Value) & {invertedMaskHex}));");
        }
        else
        {
            sb.AppendLine($"{indent}public {info.TypeName} With{flag.Name}(bool value) => new(value ? ({info.StorageType})(Value | {maskHex}) : ({info.StorageType})(Value & {invertedMaskHex}));");
        }
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a With{Name} method for a BitField that returns a new struct with the field set to a value.
    /// </summary>
    private static void GenerateWithBitFieldMethod(StringBuilder sb, BitFieldsInfo info, BitFieldInfo field, string indent)
    {
        int shift = field.Shift;

        // Reference the named mask constants generated by GenerateFieldConstants
        string snakeName = ToUpperSnakeCase(field.Name);
        string shiftedMaskHex = shift > 0 ? $"{snakeName}_SHIFTED_MASK" : $"{snakeName}_MASK";
        string invertedMaskHex = $"{snakeName}_INVERTED_MASK";

        sb.AppendLine($"{indent}/// <summary>Returns a new {info.TypeName} with the {field.Name} field set to the specified value.</summary>");
        sb.AppendLine($"{indent}[MethodImpl(MethodImplOptions.AggressiveInlining)]");

        if (info.StorageTypeIsSigned)
        {
            if (shift == 0)
            {
                sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value) => new(({info.StorageType})(((({info.UnsignedStorageType})Value) & {invertedMaskHex}) | (({info.UnsignedStorageType})value & {shiftedMaskHex})));");
            }
            else
            {
                sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value) => new(({info.StorageType})(((({info.UnsignedStorageType})Value) & {invertedMaskHex}) | (((({info.UnsignedStorageType})value) << {shift}) & {shiftedMaskHex})));");
            }
        }
        else
        {
            if (shift == 0)
            {
                sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value) => new(({info.StorageType})((Value & {invertedMaskHex}) | (({info.StorageType})value & {shiftedMaskHex})));");
            }
            else
            {
                sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value) => new(({info.StorageType})((Value & {invertedMaskHex}) | ((({info.StorageType})value << {shift}) & {shiftedMaskHex})));");
            }
        }
        sb.AppendLine();
    }

    /// <summary>
    /// Generates named mask constants for all fields and flags, decomposed into
    /// component constants (mask, shifted mask, inverted mask) so that reviewers
    /// can easily verify the derivation of each value.
    /// </summary>
    private static void GenerateFieldConstants(StringBuilder sb, BitFieldsInfo info, string indent)
    {
        string maskType = info.StorageTypeIsSigned ? info.UnsignedStorageType : info.StorageType;

        sb.AppendLine($"{indent}// --- Bit field mask constants ---");

        foreach (var field in info.Fields)
        {
            int shift = field.Shift;
            int width = field.Width;
            ulong mask = (1UL << width) - 1;
            ulong shiftedMask = mask << shift;
            ulong invertedShiftedMask = ~shiftedMask;
            string snakeName = ToUpperSnakeCase(field.Name);

            sb.AppendLine($"{indent}// {field.Name}: bits [{shift}..{shift + width - 1}], width {width}");
            sb.AppendLine($"{indent}private const {maskType} {snakeName}_MASK = {FormatHex(mask, maskType)};");
            if (shift > 0)
                sb.AppendLine($"{indent}private const {maskType} {snakeName}_SHIFTED_MASK = {FormatHex(shiftedMask, maskType)};  // {snakeName}_MASK << {shift}");
            sb.AppendLine($"{indent}private const {maskType} {snakeName}_INVERTED_MASK = {FormatHex(invertedShiftedMask, maskType)};  // ~{(shift > 0 ? $"{snakeName}_SHIFTED_MASK" : $"{snakeName}_MASK")}");
        }

        foreach (var flag in info.Flags)
        {
            int bit = flag.Bit;
            ulong mask = 1UL << bit;
            ulong invertedMask = ~mask;
            string snakeName = ToUpperSnakeCase(flag.Name);

            sb.AppendLine($"{indent}// {flag.Name}: bit {bit}");
            sb.AppendLine($"{indent}private const {maskType} {snakeName}_MASK = {FormatHex(mask, maskType)};");
            sb.AppendLine($"{indent}private const {maskType} {snakeName}_INVERTED_MASK = {FormatHex(invertedMask, maskType)};  // ~{snakeName}_MASK");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Generates named constants for the constructor normalization masks
    /// (combined MustBe + UndefinedBitsMustBe constraints) with comments
    /// listing which fields and flags contribute to each mask.
    /// </summary>
    private static void GenerateNormalizationConstants(StringBuilder sb, BitFieldsInfo info,
        ulong mustClearMask, ulong mustSetMask, ulong allBitsMask, string indent)
    {
        bool hasClear = mustClearMask != 0;
        bool hasSet = mustSetMask != 0;
        if (!hasClear && !hasSet)
            return;

        string maskType = info.StorageTypeIsSigned ? info.UnsignedStorageType : info.StorageType;

        sb.AppendLine($"{indent}// --- Constructor normalization masks ---");

        if (hasClear)
        {
            var contributors = new System.Collections.Generic.List<string>();
            foreach (var f in info.Fields)
                if (f.ValueOverride == MustBe.Zero) contributors.Add($"{f.Name} (MustBe.Zero)");
            foreach (var f in info.Flags)
                if (f.ValueOverride == MustBe.Zero) contributors.Add($"{f.Name} (MustBe.Zero)");
            if (info.UndefinedBitsMode == UndefinedBitsMustBe.Zeroes)
                contributors.Add("undefined bits (UndefinedBitsMustBe.Zeroes)");

            string comment = contributors.Count > 0
                ? $"  // Clears: {string.Join(", ", contributors)}"
                : "";
            sb.AppendLine($"{indent}private const {maskType} NORMALIZATION_AND_MASK = {FormatHex(~mustClearMask & allBitsMask, maskType)};{comment}");
        }

        if (hasSet)
        {
            var contributors = new System.Collections.Generic.List<string>();
            foreach (var f in info.Fields)
                if (f.ValueOverride == MustBe.One) contributors.Add($"{f.Name} (MustBe.One)");
            foreach (var f in info.Flags)
                if (f.ValueOverride == MustBe.One) contributors.Add($"{f.Name} (MustBe.One)");
            if (info.UndefinedBitsMode == UndefinedBitsMustBe.Ones)
                contributors.Add("undefined bits (UndefinedBitsMustBe.Ones)");

            string comment = contributors.Count > 0
                ? $"  // Sets: {string.Join(", ", contributors)}"
                : "";
            sb.AppendLine($"{indent}private const {maskType} NORMALIZATION_OR_MASK = {FormatHex(mustSetMask, maskType)};{comment}");
        }

        sb.AppendLine();
    }
}
