using System.Text;
using System;

namespace Stardust.Generators;

public partial class BitFieldsGenerator
{
    /// <summary>
    /// Generates a BitField property referencing named mask constants for maximum performance.
    /// For signed property types (sbyte, short, int, long), sign extension is performed
    /// when the field width is smaller than the property type width.
    /// For floating-point property types (Half, float, double), the getter wraps the
    /// extracted bits with <c>BitConverter.*BitsTo*</c> and the setter converts with
    /// <c>BitConverter.*To*Bits</c> before inserting into the storage word.
    /// </summary>
    private static void GenerateBitFieldProperty(StringBuilder sb, BitFieldsInfo info, BitFieldInfo field, string indent)
    {
        int shift = field.Shift;
        int width = field.Width;
        int end = shift + width - 1;

        // Reference the named mask constants generated by GenerateFieldConstants
        string snakeName = "__" + ToUpperSnakeCase(field.Name);
        string startBitConst = $"{snakeName}_START_BIT";
        string maskHex = $"{snakeName}_MASK";
        string shiftedMaskHex = shift > 0 ? $"{snakeName}_SHIFTED_MASK" : $"{snakeName}_MASK";
        string invertedMaskHex = $"{snakeName}_INVERTED_MASK";

        // Check if the property type is signed and needs sign extension
        bool propertyTypeIsSigned = IsSignedType(field.PropertyType);
        int propertyTypeBitWidth = GetTypeBitWidth(field.PropertyType);
        bool needsSignExtension = propertyTypeIsSigned && width < propertyTypeBitWidth;

        // Check if the property type is a floating-point type that needs BitConverter wrapping
        bool isFloatProp = IsFloatingPointPropertyType(field.PropertyType);

        // Check if the property type is an embedded [BitFields] struct that needs
        // cast chains through its native storage type (NativeType != PropertyType, not float)
        bool isEmbeddedStruct = field.NativeType != field.PropertyType && !isFloatProp;

        // Saturating: clamp value to the field's valid range before inserting into storage.
        // Only applies for non-float, non-embedded, non-MustBe fields that are narrower than
        // their property type (so the clamp actually changes behaviour vs. the mask).
        bool canSaturate = !isFloatProp && !isEmbeddedStruct
            && field.Saturating
            && GeneratorUtils.IsSaturatablePropertyType(field.PropertyType)
            && field.Width < GetTypeBitWidth(field.PropertyType)
            && field.ValueOverride == MustBe.Any;

        sb.AppendLine($"{indent}public partial {field.PropertyType} {field.Name}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");

        // Getter: For signed property types with field width < type width, perform sign extension
        if (needsSignExtension)
        {
            // Optimized sign extension: mask in place, then shift left/right for sign extension.
            // This is more efficient than extract-then-extend (saves one shift operation).
            // Formula: ((signExtendType)(__value & shiftedMask) << leftShift) >> rightShift
            // - leftShift positions the field's MSB at the sign bit of the intermediate type
            // - rightShift propagates the sign and moves the result to bits [0, width-1]
            string signExtendType = GetSignExtendIntermediateType(field.PropertyType);
            int intermediateTypeBitWidth = signExtendType == "long" ? 64 : 32;
            int leftShift = intermediateTypeBitWidth - 1 - end;  // Put field MSB at bit 31 (or 63)
            int rightShift = intermediateTypeBitWidth - width;       // Propagate sign to result width

            if (info.NeedsUnsignedCast)
            {
                // For signed storage or nint/nuint, cast to unsigned first to avoid unwanted sign extension
                sb.AppendLine($"{indent}    get => ({field.PropertyType})((({signExtendType})((({info.UnsignedStorageType})__value) & {shiftedMaskHex}) << {leftShift}) >> {rightShift});");
            }
            else
            {
                sb.AppendLine($"{indent}    get => ({field.PropertyType})((({signExtendType})(__value & {shiftedMaskHex}) << {leftShift}) >> {rightShift});");
            }
        }
        else if (isFloatProp)
        {
            // Floating-point property: extract raw bits as unsigned integer, then convert via BitConverter.
            // E.g., BitConverter.UInt16BitsToHalf((ushort)((__value >> START_BIT) & MASK))
            string fromBits = FloatPropertyFromBits(field.PropertyType);
            string unsignedType = FloatPropertyUnsignedType(field.PropertyType);

            if (info.NeedsUnsignedCast)
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}    get => {fromBits}(({unsignedType})((({info.UnsignedStorageType})__value) & {maskHex}));");
                else
                    sb.AppendLine($"{indent}    get => {fromBits}(({unsignedType})(((({info.UnsignedStorageType})__value) >> {startBitConst}) & {maskHex}));");
            }
            else
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}    get => {fromBits}(({unsignedType})(__value & {maskHex}));");
                else
                    sb.AppendLine($"{indent}    get => {fromBits}(({unsignedType})((__value >> {startBitConst}) & {maskHex}));");
            }
        }
        else if (isEmbeddedStruct)
        {
            // Embedded [BitFields] struct: extract raw bits, cast to native storage type,
            // then convert to struct type via implicit operator.
            // E.g., (MyStruct)(byte)((__value >> START_BIT) & MASK)
            if (info.NeedsUnsignedCast)
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})(({field.NativeType})((({info.UnsignedStorageType})__value) & {maskHex}));");
                else
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})(({field.NativeType})(((({info.UnsignedStorageType})__value) >> {startBitConst}) & {maskHex}));");
            }
            else
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})(({field.NativeType})(__value & {maskHex}));");
                else
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})(({field.NativeType})((__value >> {startBitConst}) & {maskHex}));");
            }
        }
        else
        {
            if (info.NeedsUnsignedCast)
            {
                if (shift == 0)
                {
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})((({info.UnsignedStorageType})__value) & {maskHex});");
                }
                else
                {
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})(((({info.UnsignedStorageType})__value) >> {startBitConst}) & {maskHex});");
                }
            }
            else
            {
                if (shift == 0)
                {
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})(__value & {maskHex});");
                }
                else
                {
                    sb.AppendLine($"{indent}    get => ({field.PropertyType})((__value >> {startBitConst}) & {maskHex});");
                }
            }
        }

        sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");

        // For floating-point property types in the setter, convert value to raw bits first.
        // E.g., "var bits = BitConverter.HalfToUInt16Bits(value);" then use bits instead of value.
        // For MustBe overrides, the floating-point value is ignored so no conversion is needed.
        string setterValueExpr = "value";
        if (isFloatProp && field.ValueOverride == MustBe.Any)
        {
            setterValueExpr = "__bits";
        }

        // Setter: enforce MustBe constraints, or do normal read-modify-write
        if (field.ValueOverride == MustBe.Zero)
        {
            // MustBe.Zero: always clear the field bits regardless of input
            if (info.NeedsUnsignedCast)
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})((({info.UnsignedStorageType})__value) & {invertedMaskHex});");
            else
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})(__value & {invertedMaskHex});");
        }
        else if (field.ValueOverride == MustBe.One)
        {
            // MustBe.One: always set the field bits regardless of input
            if (info.NeedsUnsignedCast)
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})((({info.UnsignedStorageType})__value) | {shiftedMaskHex});");
            else
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})(__value | {shiftedMaskHex});");
        }
        else if (isFloatProp)
        {
            // Floating-point setter: convert to raw bits, then insert into storage word.
            string toBits = FloatPropertyToBits(field.PropertyType);
            sb.AppendLine($"{indent}    set {{ var {setterValueExpr} = {toBits}(value);");
            if (info.NeedsUnsignedCast)
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | ((({info.UnsignedStorageType}){setterValueExpr}) & {shiftedMaskHex}));");
                else
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | (((({info.UnsignedStorageType}){setterValueExpr}) << {startBitConst}) & {shiftedMaskHex}));");
            }
            else
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})((__value & {invertedMaskHex}) | ((({info.StorageType}){setterValueExpr}) & {shiftedMaskHex}));");
                else
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})((__value & {invertedMaskHex}) | (((({info.StorageType}){setterValueExpr}) << {startBitConst}) & {shiftedMaskHex}));");
            }
            sb.AppendLine($"{indent}    }}");
        }
        else if (isEmbeddedStruct)
        {
            // Embedded struct setter: convert to native type via implicit operator, then insert bits.
            sb.AppendLine($"{indent}    set {{ var __ev = ({field.NativeType})value;");
            if (info.NeedsUnsignedCast)
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | ((({info.UnsignedStorageType})__ev) & {shiftedMaskHex}));");
                else
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | (((({info.UnsignedStorageType})__ev) << {startBitConst}) & {shiftedMaskHex}));");
            }
            else
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})((__value & {invertedMaskHex}) | ((({info.StorageType})__ev) & {shiftedMaskHex}));");
                else
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})((__value & {invertedMaskHex}) | (((({info.StorageType})__ev) << {startBitConst}) & {shiftedMaskHex}));");
            }
            sb.AppendLine($"{indent}    }}");
        }
        else if (canSaturate)
        {
            // Saturating setter: clamp value to the field's valid range, then read-modify-write.
            string satClampExpr = GeneratorUtils.BuildSatClampExpr(
                field.PropertyType, IsSignedType(field.PropertyType),
                $"{snakeName}_SAT_MIN", $"{snakeName}_SAT_MAX");
            sb.AppendLine($"{indent}    set");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var __sat = {satClampExpr};");
            if (info.NeedsUnsignedCast)
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | ((({info.UnsignedStorageType})__sat) & {shiftedMaskHex}));");
                else
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | (((({info.UnsignedStorageType})__sat) << {startBitConst}) & {shiftedMaskHex}));");
            }
            else
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})((__value & {invertedMaskHex}) | ((({info.StorageType})__sat) & {shiftedMaskHex}));");
                else
                    sb.AppendLine($"{indent}        __value = ({info.StorageType})((__value & {invertedMaskHex}) | (((({info.StorageType})__sat) << {startBitConst}) & {shiftedMaskHex}));");
            }
            sb.AppendLine($"{indent}    }}");
        }
        else if (info.NeedsUnsignedCast)
        {
            if (shift == 0)
            {
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | ((({info.UnsignedStorageType})value) & {shiftedMaskHex}));");
            }
            else
            {
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | (((({info.UnsignedStorageType})value) << {startBitConst}) & {shiftedMaskHex}));");
            }
        }
        else
        {
            if (shift == 0)
            {
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})((__value & {invertedMaskHex}) | ((({info.StorageType})value) & {shiftedMaskHex}));");
            }
            else
            {
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})((__value & {invertedMaskHex}) | (((({info.StorageType})value) << {startBitConst}) & {shiftedMaskHex}));");
            }
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a BitFlag property referencing named mask constants for maximum performance.
    /// </summary>
    private static void GenerateBitFlagProperty(StringBuilder sb, BitFieldsInfo info, BitFlagInfo flag, string indent)
    {
        // Reference the named mask constants generated by GenerateFieldConstants
        string snakeName = "__" + ToUpperSnakeCase(flag.Name);
        string maskHex = $"{snakeName}_MASK";
        string invertedMaskHex = $"{snakeName}_INVERTED_MASK";

        sb.AppendLine($"{indent}public partial bool {flag.Name}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        
        if (flag.ValueOverride == MustBe.Zero)
        {
            // MustBe.Zero: getter always false, setter always clears
            sb.AppendLine($"{indent}    get => false;");
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            if (info.NeedsUnsignedCast)
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})((({info.UnsignedStorageType})__value) & {invertedMaskHex});");
            else
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})(__value & {invertedMaskHex});");
        }
        else if (flag.ValueOverride == MustBe.One)
        {
            // MustBe.One: getter always true, setter always sets
            sb.AppendLine($"{indent}    get => true;");
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            if (info.NeedsUnsignedCast)
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})((({info.UnsignedStorageType})__value) | {maskHex});");
            else
                sb.AppendLine($"{indent}    set => __value = ({info.StorageType})(__value | {maskHex});");
        }
        else if (info.NeedsUnsignedCast)
        {
            sb.AppendLine($"{indent}    get => ((({info.UnsignedStorageType})__value) & {maskHex}) != 0;");
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    set => __value = value ? ({info.StorageType})((({info.UnsignedStorageType})__value) | {maskHex}) : ({info.StorageType})((({info.UnsignedStorageType})__value) & {invertedMaskHex});");
        }
        else
        {
            sb.AppendLine($"{indent}    get => (__value & {maskHex}) != 0;");
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    set => __value = value ? ({info.StorageType})(__value | {maskHex}) : ({info.StorageType})(__value & {invertedMaskHex});");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a static property that returns a struct with only the specified bit set.
    /// </summary>
    private static void GenerateStaticBitProperty(StringBuilder sb, BitFieldsInfo info, BitFlagInfo flag, string indent)
    {
        string maskRef = $"{"__" + ToUpperSnakeCase(flag.Name)}_MASK";

        string castExpr = info.StorageTypeIsSigned
            ? $"unchecked(({info.StorageType}){maskRef})"
            : info.IsNativeIntegerType
                ? $"unchecked(({info.StorageType}){maskRef})"
                : maskRef;

        sb.AppendLine($"{indent}/// <summary>Returns a {info.TypeName} with only the {flag.Name} bit set.</summary>");
        sb.AppendLine($"{indent}public static {info.TypeName} {flag.Name}Bit => new({castExpr});");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a static property that returns a struct with the mask for the specified field.
    /// </summary>
    private static void GenerateStaticMaskProperty(StringBuilder sb, BitFieldsInfo info, BitFieldInfo field, string indent)
    {
        string snakeName = "__" + ToUpperSnakeCase(field.Name);
        string shiftedMaskRef = field.Shift > 0 ? $"{snakeName}_SHIFTED_MASK" : $"{snakeName}_MASK";

        string castExpr = info.StorageTypeIsSigned
            ? $"unchecked(({info.StorageType}){shiftedMaskRef})"
            : info.IsNativeIntegerType
                ? $"unchecked(({info.StorageType}){shiftedMaskRef})"
                : shiftedMaskRef;

        sb.AppendLine($"{indent}/// <summary>Returns a {info.TypeName} with the mask for the {field.Name} field (bits {field.Shift}-{field.Shift + field.Width - 1}).</summary>");
        sb.AppendLine($"{indent}public static {info.TypeName} {field.Name}Mask => new({castExpr});");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a With{Name} method for a BitFlag that returns a new struct with the flag set/cleared.
    /// </summary>
    private static void GenerateWithBitFlagMethod(StringBuilder sb, BitFieldsInfo info, BitFlagInfo flag, string indent)
    {
        // Reference the named mask constants generated by GenerateFieldConstants
        string snakeName = "__" + ToUpperSnakeCase(flag.Name);
        string maskHex = $"{snakeName}_MASK";
        string invertedMaskHex = $"{snakeName}_INVERTED_MASK";

        sb.AppendLine($"{indent}/// <summary>Returns a new {info.TypeName} with the {flag.Name} flag set to the specified value.</summary>");
        sb.AppendLine($"{indent}[MethodImpl(MethodImplOptions.AggressiveInlining)]");

        if (info.NeedsUnsignedCast)
        {
            sb.AppendLine($"{indent}public {info.TypeName} With{flag.Name}(bool value) => new(value ? ({info.StorageType})((({info.UnsignedStorageType})__value) | {maskHex}) : ({info.StorageType})((({info.UnsignedStorageType})__value) & {invertedMaskHex}));");
        }
        else
        {
            sb.AppendLine($"{indent}public {info.TypeName} With{flag.Name}(bool value) => new(value ? ({info.StorageType})(__value | {maskHex}) : ({info.StorageType})(__value & {invertedMaskHex}));");
        }
        sb.AppendLine();
    }

    /// <summary>
    /// Generates a With{Name} method for a BitField that returns a new struct with the field set to a value.
    /// </summary>
    private static void GenerateWithBitFieldMethod(StringBuilder sb, BitFieldsInfo info, BitFieldInfo field, string indent)
    {
        int shift = field.Shift;

        // Reference the named mask constants generated by GenerateFieldConstants
        string snakeName = "__" + ToUpperSnakeCase(field.Name);
        string startBitConst = $"{snakeName}_START_BIT";
        string shiftedMaskHex = shift > 0 ? $"{snakeName}_SHIFTED_MASK" : $"{snakeName}_MASK";
        string invertedMaskHex = $"{snakeName}_INVERTED_MASK";

        // For floating-point property types, wrap `value` with BitConverter.*To*Bits(value)
        bool isFloatProp = IsFloatingPointPropertyType(field.PropertyType);
        bool isEmbeddedStruct = field.NativeType != field.PropertyType && !isFloatProp;
        string valueExpr = isFloatProp ? $"{FloatPropertyToBits(field.PropertyType)}(value)" : "value";

        // Saturating: clamp in With method too
        bool canSaturate = !isFloatProp && !isEmbeddedStruct
            && field.Saturating
            && GeneratorUtils.IsSaturatablePropertyType(field.PropertyType)
            && field.Width < GetTypeBitWidth(field.PropertyType)
            && field.ValueOverride == MustBe.Any;

        sb.AppendLine($"{indent}/// <summary>Returns a new {info.TypeName} with the {field.Name} field set to the specified value.</summary>");
        sb.AppendLine($"{indent}[MethodImpl(MethodImplOptions.AggressiveInlining)]");

        if (canSaturate)
        {
            // Block form with saturation clamp
            string satClampExpr = GeneratorUtils.BuildSatClampExpr(
                field.PropertyType, IsSignedType(field.PropertyType),
                $"{snakeName}_SAT_MIN", $"{snakeName}_SAT_MAX");
            string sv = "__sat";

            sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    var {sv} = {satClampExpr};");
            if (info.StorageTypeIsSigned)
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}    return new(({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | (({info.UnsignedStorageType}){sv} & {shiftedMaskHex})));");
                else
                    sb.AppendLine($"{indent}    return new(({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | (((({info.UnsignedStorageType}){sv}) << {startBitConst}) & {shiftedMaskHex})));");
            }
            else
            {
                if (shift == 0)
                    sb.AppendLine($"{indent}    return new(({info.StorageType})((__value & {invertedMaskHex}) | (({info.StorageType}){sv} & {shiftedMaskHex})));");
                else
                    sb.AppendLine($"{indent}    return new(({info.StorageType})((__value & {invertedMaskHex}) | ((({info.StorageType}){sv} << {startBitConst}) & {shiftedMaskHex})));");
            }
            sb.AppendLine($"{indent}}}");
        }
        else if (info.StorageTypeIsSigned)
        {
            if (shift == 0)
            {
                sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value) => new(({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | (({info.UnsignedStorageType}){valueExpr} & {shiftedMaskHex})));");
            }
            else
            {
                sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value) => new(({info.StorageType})(((({info.UnsignedStorageType})__value) & {invertedMaskHex}) | (((({info.UnsignedStorageType}){valueExpr}) << {startBitConst}) & {shiftedMaskHex})));");
            }
        }
        else
        {
            if (shift == 0)
            {
                sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value) => new(({info.StorageType})((__value & {invertedMaskHex}) | (({info.StorageType}){valueExpr} & {shiftedMaskHex})));");
            }
            else
            {
                sb.AppendLine($"{indent}public {info.TypeName} With{field.Name}({field.PropertyType} value) => new(({info.StorageType})((__value & {invertedMaskHex}) | ((({info.StorageType}){valueExpr} << {startBitConst}) & {shiftedMaskHex})));");
            }
        }
        sb.AppendLine();
    }

    /// <summary>
    /// Generates named mask constants for all fields and flags, decomposed into
    /// component constants (mask, shifted mask, inverted mask) so that reviewers
    /// can easily verify the derivation of each value.
    /// </summary>
    private static void GenerateFieldConstants(StringBuilder sb, BitFieldsInfo info, string indent)
    {
        string maskType = info.NeedsUnsignedCast ? info.UnsignedStorageType : info.StorageType;

        sb.AppendLine($"{indent}// --- Bit field mask constants ---");

        foreach (var field in info.Fields)
        {
            int shift = field.Shift;
            int width = field.Width;
            ulong mask = (width >= 64) ? ulong.MaxValue : (1UL << width) - 1;
            ulong shiftedMask = mask << shift;
            ulong invertedShiftedMask = ~shiftedMask;
            string snakeName = "__" + ToUpperSnakeCase(field.Name);

            sb.AppendLine($"{indent}// {field.Name}: bits [{shift}..{shift + width - 1}], width {width}");
            sb.AppendLine($"{indent}private const int {snakeName}_START_BIT = {shift};");
            sb.AppendLine($"{indent}private const {maskType} {snakeName}_MASK = {FormatHex(mask, maskType)};");
            if (shift > 0)
                sb.AppendLine($"{indent}private const {maskType} {snakeName}_SHIFTED_MASK = {FormatHex(shiftedMask, maskType)};  // {snakeName}_MASK << {snakeName}_START_BIT");
            sb.AppendLine($"{indent}private const {maskType} {snakeName}_INVERTED_MASK = {FormatHex(invertedShiftedMask, maskType)};  // ~{(shift > 0 ? $"{snakeName}_SHIFTED_MASK" : $"{snakeName}_MASK")}");

            // Saturation constants (only emitted when Saturating=true and the field is narrower
            // than its property type, so the clamp actually changes behaviour).
            if (field.Saturating && GeneratorUtils.IsSaturatablePropertyType(field.PropertyType)
                && width < GetTypeBitWidth(field.PropertyType))
            {
                bool satSigned = IsSignedType(field.PropertyType);
                string satConstType = GeneratorUtils.GetSatConstType(field.PropertyType);
                if (satSigned)
                {
                    long satMin = -(1L << (width - 1));
                    long satMax = (1L << (width - 1)) - 1;
                    sb.AppendLine($"{indent}private const {satConstType} {snakeName}_SAT_MIN = {GeneratorUtils.FormatSignedSatLiteral(satMin, satConstType)};  // saturating: min for {width}-bit signed field");
                    sb.AppendLine($"{indent}private const {satConstType} {snakeName}_SAT_MAX = {GeneratorUtils.FormatSignedSatLiteral(satMax, satConstType)};  // saturating: max for {width}-bit signed field");
                }
                else
                {
                    ulong satMax = (1UL << width) - 1;
                    sb.AppendLine($"{indent}private const {satConstType} {snakeName}_SAT_MAX = {GeneratorUtils.FormatUnsignedSatLiteral(satMax, satConstType)};  // saturating: max for {width}-bit unsigned field");
                }
            }
        }

        foreach (var flag in info.Flags)
        {
            int bit = flag.Bit;
            ulong mask = 1UL << bit;
            ulong invertedMask = ~mask;
            string snakeName = "__" + ToUpperSnakeCase(flag.Name);

            sb.AppendLine($"{indent}// {flag.Name}: bit {bit}");
            sb.AppendLine($"{indent}private const int {snakeName}_BIT = {bit};");
            sb.AppendLine($"{indent}private const {maskType} {snakeName}_MASK = {FormatHex(mask, maskType)};  // 1 << {snakeName}_BIT");
            sb.AppendLine($"{indent}private const {maskType} {snakeName}_INVERTED_MASK = {FormatHex(invertedMask, maskType)};  // ~{snakeName}_MASK");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Generates named constants for the constructor normalization masks
    /// (combined MustBe + UndefinedBitsMustBe constraints) with comments
    /// listing which fields and flags contribute to each mask.
    /// </summary>
    private static void GenerateNormalizationConstants(StringBuilder sb, BitFieldsInfo info,
        ulong mustClearMask, ulong mustSetMask, ulong allBitsMask, string indent)
    {
        bool hasClear = mustClearMask != 0;
        bool hasSet = mustSetMask != 0;
        if (!hasClear && !hasSet)
            return;

        string maskType = info.NeedsUnsignedCast ? info.UnsignedStorageType : info.StorageType;

        sb.AppendLine($"{indent}// --- Constructor normalization masks ---");

        if (hasClear)
        {
            var contributors = new System.Collections.Generic.List<string>();
            foreach (var f in info.Fields)
                if (f.ValueOverride == MustBe.Zero) contributors.Add($"{f.Name} (MustBe.Zero)");
            foreach (var f in info.Flags)
                if (f.ValueOverride == MustBe.Zero) contributors.Add($"{f.Name} (MustBe.Zero)");
            if (info.UndefinedBitsMode == UndefinedBitsMustBe.Zeroes)
                contributors.Add("undefined bits (UndefinedBitsMustBe.Zeroes)");

            string comment = contributors.Count > 0
                ? $"  // Clears: {string.Join(", ", contributors)}"
                : "";
            sb.AppendLine($"{indent}private const {maskType} __NORMALIZATION_AND_MASK = {FormatHex(~mustClearMask & allBitsMask, maskType)};{comment}");
        }

        if (hasSet)
        {
            var contributors = new System.Collections.Generic.List<string>();
            foreach (var f in info.Fields)
                if (f.ValueOverride == MustBe.One) contributors.Add($"{f.Name} (MustBe.One)");
            foreach (var f in info.Flags)
                if (f.ValueOverride == MustBe.One) contributors.Add($"{f.Name} (MustBe.One)");
            if (info.UndefinedBitsMode == UndefinedBitsMustBe.Ones)
                contributors.Add("undefined bits (UndefinedBitsMustBe.Ones)");

            string comment = contributors.Count > 0
                ? $"  // Sets: {string.Join(", ", contributors)}"
                : "";
            sb.AppendLine($"{indent}private const {maskType} __NORMALIZATION_OR_MASK = {FormatHex(mustSetMask, maskType)};{comment}");
        }

        sb.AppendLine();
    }
}
